# Site settings
title: Maki Mühendislik & Mekanik Tesisat, Seyhan/Adana
email: info@makimuhendislik.com.tr
url: http://www.makimuhendislik.com.tr
description: "Maki Mühendislik & Mekanik Tesisat, Seyhan/Adana"
keywords: "Maki Mühendislik, Adana, Adana Mühendislik, Adana Mekanik Tesisat, Maki Mekanik, Maki Mekanik Tesisat"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#de7f3c'

# Footer settings
footer: Maki Mühendislik

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://www.twitter.com/makimuhendislik
  - title: facebook
    url: https://www.facebook.com/makimuhendislik

# Build settings
markdown: kramdown
permalink: pretty

# Gems
gems:
  - jekyll-sitemap
